### ISSUE TITLE
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by tanyingjia** [divelab/DIG#103]
When I run the 3D Diagram tutorial, an error occurs. I don't know how to use it.

Traceback (most recent call last):
  File "D:\rubbihs\pyg\mol\3d\qm9.py", line 14, in <module>
    model = SphereNet(energy_and_force=False, cutoff=5.0, num_layers=4,
  File "D:\down\anaconda\envs\pyg\lib\site-packages\dig\threedgraph\method\spherenet\spherenet.py", line 265, in __init__
    self.emb = emb(num_spherical, num_radial, self.cutoff, envelope_exponent)
  File "D:\down\anaconda\envs\pyg\lib\site-packages\dig\threedgraph\method\spherenet\spherenet.py", line 23, in __init__
    self.dist_emb = dist_emb(num_radial, cutoff, envelope_exponent)
  File "D:\down\anaconda\envs\pyg\lib\site-packages\dig\threedgraph\method\spherenet\features.py", line 178, in __init__
    self.reset_parameters()
  File "D:\down\anaconda\envs\pyg\lib\site-packages\dig\threedgraph\method\spherenet\features.py", line 181, in reset_parameters
    torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by limei0307** [comment]
Hi @tanyingjia, please see [issue #77](https://github.com/divelab/DIG/issues/77). Thanks.
