### ISSUE TITLE
TypeError: draw_networkx_nodes() got an unexpected keyword argument 'num_nodes'

### ISSUE THREAD

**Issue by Ryan0v0** [divelab/DIG#12]
I finished the Installation and tried to run the demo of GradCAM, but the error happened as below. 
```shell
$ python -m benchmark.kernel.pipeline --task explain --model_name GCN_3l --dataset_name tox21 --target_idx 2 --explainer GradCAM --sparsity 0.5 --debug --vis --nolabel
Add /home/ubuntu/DIG/dig/xgraph/metrics as a system path.
DEBUG: 04/26/2021 09:26:13 AM : Parse arguments.

INFO: -----------------------------------
    Task: explain
Mon Apr 26 09:26:13 2021
INFO: Load Dataset tox21
DEBUG: 04/26/2021 09:26:13 AM :  Data(edge_attr=[22, 3], edge_index=[2, 22], smiles="CCCc1ccc(OC)cc1", x=[11, 9], y=[1])
INFO: Loading model...
INFO: GCN_3l(
  (conv1): GCNConv(9, 300)
  (convs): ModuleList(
    (0): GCNConv(300, 300)
    (1): GCNConv(300, 300)
  )
  (relu1): ReLU()
  (relus): ModuleList(
    (0): ReLU()
    (1): ReLU()
  )
  (readout): GlobalMeanPool()
  (ffn): Sequential(
    (0): Linear(in_features=300, out_features=300, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=300, out_features=2, bias=True)
  )
  (dropout): Dropout(p=0.5, inplace=False)
)
INFO: Config the model used to be explained...
INFO: Loading best Checkpoint 932...
INFO: Create explainer: GradCAM...
INFO: Begin explain
INFO: explain graph line 1667
DEBUG: 04/26/2021 09:26:16 AM : Mask Calculate...
DEBUG: 04/26/2021 09:26:16 AM : Predict...
DEBUG: 04/26/2021 09:26:16 AM : Explainer prediction time: 0.4564
Input Tensor 0 did not already require gradients, required_grads has been set automatically.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/DIG/dig/xgraph/GradCAM/benchmark/kernel/pipeline.py", line 88, in <module>
    sample_explain(explainer, data, explain_collector, sparsity=args['explain'].sparsity)
  File "/home/ubuntu/DIG/dig/xgraph/GradCAM/benchmark/kernel/explain.py", line 116, in sample_explain
    y=data.x[:, 0] if node_idx is None else data.y, num_nodes=data.x.shape[0])
  File "/home/ubuntu/DIG/dig/xgraph/GradCAM/benchmark/models/explainers.py", line 290, in visualize_graph
    nx.draw_networkx_nodes(G, pos, node_color=node_colors, **kwargs)
TypeError: draw_networkx_nodes() got an unexpected keyword argument 'num_nodes'
```

**Comment by CM-BF** [comment]
That is because the updated networkx has added a sanity check for keywords which prevents the existence of redundant or useless keywords. Please use `networkx==2.4` instead to solve this problem.

**Comment by liwenke1** [comment]
When i change my networkx version to 2.4 ,other error happened as follow
`ERROR: 12/09/2021 03:09:20 PM - utils.py - line 87 : Traceback (most recent call last):
  File "/home/DIG-main/dig/xgraph/GNNExplainer/benchmark/kernel/pipeline.py", line 115, in <module>
    sample_explain(explainer, data,explain_collector, sparsity=args['explain'].sparsity)
  File "/home/DIG-main/dig/xgraph/GNNExplainer/benchmark/kernel/explain.py", line 114, in sample_explain
    ax, G = explainer.visualize_graph(node_idx=0 if node_idx is None else node_idx, edge_index=data.edge_index,
  File "/home/DIG-main/dig/xgraph/GNNExplainer/benchmark/models/explainers.py", line 295, in visualize_graph
    nx.draw_networkx_nodes(G, pos, node_color=node_colors, **kwargs)
TypeError: draw_networkx_nodes() got an unexpected keyword argument 'num_nodes'`

**Comment by LiarLiu01** [comment]
> 这是因为更新后的 networkx 为关键字添加了健全性检查，以防止存在冗余或无用的关键字。请改用`networkx==2.4`来解决这个问题。我刚刚验证了使用正确版本的networkx，它可以正常工作。

How do you use networkx==2.4?
