### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by Never-yu** [divelab/DIG#130]
Hello, I am trying to install the packages required by PGExplainer, but I have encountered a problem that I cannot solve. I hope to get your help.thx
The problem is as follows:

pip install cilog typed-argument-parser==1.5.4 tqdm
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\Scripts\pip-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\configuration.py", line 24, in <module>
    from pip._internal.utils import appdirs
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 33, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 29, in _set_platform_dir_class
    result: type[PlatformDirsABC] = getattr(importlib.import_module(module), name)
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\ctypes\__init__.py", line 8, in <module>
    import numpy as np
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\numpy\__init__.py", line 162, in <module>
    from . import ctypeslib
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\numpy\ctypeslib.py", line 85, in <module>
    c_intp = nic._getintp_ctype()
  File "D:\Anaconda\Anaconda3-2021.05\envs\xgraph\lib\site-packages\numpy\core\_internal.py", line 231, in _getintp_ctype
    val = ctypes.c_long
AttributeError: module 'ctypes' has no attribute 'c_long'
?[0m

**Comment by CM-BF** [comment]
Thank you for your issue!
Are you sure about you are installing the right version of DIG?
At least, the version of `typed-argument-parser` is 1.7.2 instead of 1.5.4. And these packages should be installed automatically by typing:
```bash
pip install dive-into-graphs
```
Please refer to the branch [`dig-stable`](https://github.com/divelab/DIG), and follow the instruction.

**Comment by Never-yu** [comment]
Thanks for your help.
It looks like I need to upgrade the DIG to a right version.
