### ISSUE TITLE
No module named 'torch_geometric.nn.acts'

### ISSUE THREAD

**Issue by pearl-rabbit** [divelab/DIG#179]
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from dig.threedgraph.method import SphereNet
  File "/python3.7/site-packages/dig/threedgraph/method/__init__.py", line 3, in <module>
    from .dimenetpp import DimeNetPP
  File "/python3.7/site-packages/dig/threedgraph/method/dimenetpp/__init__.py", line 1, in <module>
    from .dimenetpp import DimeNetPP
  File "/py_test37/lib/python3.7/site-packages/dig/threedgraph/method/dimenetpp/dimenetpp.py", line 4, in <module>
    from torch_geometric.nn.acts import swish
ModuleNotFoundError: No module named 'torch_geometric.nn.acts'

I encountered this problem when using the threegraph example. How can I solve it?

**Comment by vict0rsch** [comment]
I have the same issue

**Comment by Michael-Hai** [comment]
can try:

try:
     from torch_geometric.nn.acts import swish
except ImportError:
    from torch_geometric.nn.resolver import swish

**Comment by SaraiQX** [comment]
Many thanks to Michael-Hai.

```
try:
from torch_geometric.nn.acts import swish
except ImportError:
from torch_geometric.nn.resolver import swish
```
Worked okay.

**Comment by White-Charles** [comment]
> can try:
> 
> try: from torch_geometric.nn.acts import swish except ImportError: from torch_geometric.nn.resolver import swish

Thank Michael-Hai. very much.
