### ISSUE TITLE
Issues on SubgraphX implementation on DIG

### ISSUE THREAD

**Issue by Stika4life** [divelab/DIG#251]
Hi, I am a student working on SubgraphX implementation on DIG. I get the error below after the setup when using the dataset the code base came with , specifically Dataset :  BBBP(2039)

*******************
load example 894.
Error executing job with overrides: ['explainers=subgraphx', 'datasets.dataset_root=/home/pcshark/DIG/benchmarks/xgraph/datasets', 'models.gnn_saving_dir=/home/pcshark/DIG/benchmarks/xgraph/checkpoints', 'explainers.explanation_result_dir=/home/pcshark/DIG/benchmarks/xgraph/results', 'record_filename=/home/pcshark/DIG/benchmarks/xgraph/result_jsons']
Traceback (most recent call last):
  File "/home/pcshark/DIG/benchmarks/xgraph/subgraphx.py", line 131, in pipeline
    subgraphx.explain(data.x, data.edge_index,
  File "/home/pcshark/anaconda3/envs/pyth38/lib/python3.8/site-packages/dig/xgraph/method/subgraphx.py", line 763, in explain
    results = self.read_from_MCTSInfo_list(saved_MCTSInfo_list)
  File "/home/pcshark/anaconda3/envs/pyth38/lib/python3.8/site-packages/dig/xgraph/method/subgraphx.py", line 738, in read_from_MCTSInfo_list
    ret_list = [MCTSNode(device=self.device).load_info(node_info) for node_info in MCTSInfo_list]
  File "/home/pcshark/anaconda3/envs/pyth38/lib/python3.8/site-packages/dig/xgraph/method/subgraphx.py", line 738, in <listcomp>
    ret_list = [MCTSNode(device=self.device).load_info(node_info) for node_info in MCTSInfo_list]
  File "/home/pcshark/anaconda3/envs/pyth38/lib/python3.8/site-packages/dig/xgraph/method/subgraphx.py", line 429, in load_info
    self.data = info_dict['data'].to(self.device)
AttributeError: 'Batch' object has no attribute 'to'

***************************************
Please help. Thanks

**Comment by pcppp** [comment]
i have same problem!!!Please help. Thanks
