### ISSUE TITLE
GraphCL example error

### ISSUE THREAD

**Issue by adityauser** [divelab/DIG#30]
While running the codes in [GraphCL](https://github.com/divelab/DIG/blob/dig/benchmarks/sslgraph/example_graphcl.ipynb) at line `evaluator.evaluate(learning_model=graphcl, encoder=encoder)
`
I'm getting error:
```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    evaluator.evaluate(learning_model=graphcl, encoder=encoder)
  File "C:\ProgramData\Anaconda3\envs\dig\lib\site-packages\dig\sslgraph\evaluation\eval_graph.py", line 394, in evaluate
    for fold, train_loader, test_loader, val_loader in k_fold(
  File "C:\ProgramData\Anaconda3\envs\dig\lib\site-packages\dig\sslgraph\evaluation\eval_graph.py", line 561, in k_fold
    test_loader = DataLoader(dataset[test_indices[i]], batch_size, shuffle=False)
  File "C:\ProgramData\Anaconda3\envs\dig\lib\site-packages\torch_geometric\data\dataset.py", line 198, in __getitem__
    return self.index_select(idx)
  File "C:\ProgramData\Anaconda3\envs\dig\lib\site-packages\torch_geometric\data\dataset.py", line 224, in index_select
    raise IndexError(
IndexError: Only integers, slices (':'), list, tuples, torch.tensor and np.ndarray of dtype long or bool are valid indices (got 'Tensor')
```
I run this code:

```
from dig.sslgraph.utils import Encoder
from dig.sslgraph.evaluation import GraphSemisupervised, GraphUnsupervised
from dig.sslgraph.dataset import get_dataset
from dig.sslgraph.method import GraphCL

dataset, dataset_pretrain = get_dataset('NCI1', task='semisupervised')
feat_dim = dataset[0].x.shape[1]
embed_dim = 128

print(dataset)

encoder = Encoder(feat_dim, embed_dim, n_layers=3, gnn='resgcn')
graphcl = GraphCL(embed_dim, aug_1='subgraph', aug_2='subgraph')

evaluator = GraphSemisupervised(dataset, dataset_pretrain, label_rate=0.01)

evaluator.evaluate(learning_model=graphcl, encoder=encoder)
```
Torch version: 1.9.0 (cpu)

Any help will be highly appreciated.

**Comment by ycremar** [comment]
Hi @adityauser ,

Thank you for reporting the issue. Unfortunately, I was not able to reproduce the error in my environment. However, I have made some modifications in `dig\sslgraph\evaluation\eval_graph.py` to improve its compatibility in [this](https://github.com/divelab/DIG/commit/2cf737989608be08a78fea5f45d7179af6793af0) commit. You can install the latest version of DIG from Github (not pip) and see if the issue still happens.

If that does not work, could you try install the previous version of torch (>=1.6.0, <= 1.7.1) and pytorch-geometric (>=1.6.0, <= 1.7.1) and see if it can resolve the issue?
