### ISSUE TITLE
Errors in running the bash files in SubgraphX in the main branch

### ISSUE THREAD

**Issue by YanghepuLI** [divelab/DIG#46]
# Describe the bug
I followed the instructions in Readme in SubgraphX, created the env and installed the requirements. However I still cannot reproduce the results. When I ran the script files, I still got error and didn't know why.
```
$ cd DIG/xgraph/SubgraphX
$ source ./scripts.sh
/home/liyang/anaconda3/lib/python3.7/site-packages/numba/decorators.py:146: RuntimeWarning: Caching is not available when the 'parallel' target is in use. Caching is now being disabled to allow execution to continue.
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/home/liyang/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liyang/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/forgraph/subgraphx.py", line 6, in <module>
    from forgraph.mcts import MCTS, reward_func
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/forgraph/mcts.py", line 4, in <module>
    from Configures import mcts_args
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/Configures.py", line 3, in <module>
    from tap import Tap
  File "/home/liyang/anaconda3/lib/python3.7/site-packages/tap.py", line 6, in <module>
    from mc_bin_client import mc_bin_client, memcacheConstants as Constants
  File "/home/liyang/anaconda3/lib/python3.7/site-packages/mc_bin_client/mc_bin_client.py", line 278
    except MemcachedError, e:
                         ^
SyntaxError: invalid syntax
```
The same error also occurred when I ran another bash file.
```
$ cd DIG/xgraph/SubgraphX
$ source ./models/train_gnns.sh 
/home/liyang/anaconda3/lib/python3.7/site-packages/numba/decorators.py:146: RuntimeWarning: Caching is not available when the 'parallel' target is in use. Caching is now being disabled to allow execution to continue.
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/home/liyang/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liyang/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/models/train_gnns.py", line 9, in <module>
    from Configures import data_args, train_args, model_args
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/Configures.py", line 3, in <module>
    from tap import Tap
  File "/home/liyang/anaconda3/lib/python3.7/site-packages/tap.py", line 6, in <module>
    from mc_bin_client import mc_bin_client, memcacheConstants as Constants
  File "/home/liyang/anaconda3/lib/python3.7/site-packages/mc_bin_client/mc_bin_client.py", line 278
    except MemcachedError, e:
                         ^
SyntaxError: invalid syntax
```
# Configuration
OS: Release Linux Mint 20.2 Uma 64-bit
python version: 3.7.0
torch and cuda version: 1.9.0+cu102

**Comment by Oceanusity** [comment]
Hello, thank you for your issue.

It seems like the error comes from the dependent package [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser) which is imported as tap. However, I can't find the corresponding code `from mc_bin_client import mc_bin_client, memcacheConstants as Constants` shown above in the package source file tap.py. Could you please provide the installed package list?  Therefore, I can judge whether it's a problem of dependency package. By the way, you can try to update the tap package.

Thank you.

**Comment by Oceanusity** [comment]
By the way, the script [`install.sh`](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/install.sh) will create a virtual environment called `xgraph`. However, it seems like you run the code in your default environment here.

**Comment by YanghepuLI** [comment]
I didn't use the xgraph environment because when I used it, another problem popped up.
```
(xgraph) liyang@liyang-Lenovo-Y430P:~/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX$ source ./scripts.sh
Traceback (most recent call last):
  File "/home/liyang/anaconda3/envs/xgraph/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liyang/anaconda3/envs/xgraph/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/forgraph/subgraphx.py", line 4, in <module>
    from models import GnnNets
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/models/__init__.py", line 2, in <module>
    from models.GCN import GCNNet, GCNNet_NC
  File "/home/liyang/Documents/csprogram/DIG-main/dig/xgraph/SubgraphX/models/GCN.py", line 4, in <module>
    from torch_geometric.nn.conv import GCNConv
  File "/home/liyang/.local/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/liyang/.local/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/liyang/.local/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/liyang/.local/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/liyang/.local/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/liyang/anaconda3/envs/xgraph/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/liyang/.local/lib/python3.8/site-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```
I googled the problem, seems that the install.sh  uses conda to install torch, and it is  multi-version. So there is something wrong with the cuda.  I uninstall torch and use pip to install it in default environment, and the problem solved.  But then comes the problem in the issue.

**Comment by YanghepuLI** [comment]
My package list is as followed:
```
Package                            Version  
---------------------------------- ---------
alabaster                          0.7.11   
anaconda-client                    1.7.2    
anaconda-navigator                 1.9.2    
anaconda-project                   0.8.2    
appdirs                            1.4.3    
asn1crypto                         0.24.0   
astroid                            2.0.4    
astropy                            3.0.4    
atomicwrites                       1.2.1    
attrs                              18.2.0   
Automat                            0.7.0    
Babel                              2.6.0    
backcall                           0.1.0    
backports.shutil-get-terminal-size 1.0.0    
beautifulsoup4                     4.6.3    
bitarray                           0.8.3    
bkcharts                           0.2      
blaze                              0.11.3   
bleach                             2.1.4    
bokeh                              0.13.0   
boto                               2.49.0   
Bottleneck                         1.2.1    
certifi                            2018.8.24
cffi                               1.11.5   
chardet                            3.0.4    
click                              6.7      
cloudpickle                        0.5.5    
clyent                             1.2.2    
colorama                           0.3.9    
conda                              4.5.11   
conda-build                        3.15.1   
constantly                         15.1.0   
contextlib2                        0.5.5    
cryptography                       2.3.1    
cycler                             0.10.0   
Cython                             0.28.5   
cytoolz                            0.9.0.1  
dask                               0.19.1   
datashape                          0.5.4    
decorator                          4.3.0    
defusedxml                         0.5.0    
distributed                        1.23.1   
docutils                           0.14     
entrypoints                        0.2.3    
et-xmlfile                         1.0.1    
fastcache                          1.0.2    
filelock                           3.0.8    
Flask                              1.0.2    
Flask-Cors                         3.0.6    
gevent                             1.3.6    
glob2                              0.6      
gmpy2                              2.0.8    
googledrivedownloader              0.4      
greenlet                           0.4.15   
h5py                               2.8.0    
heapdict                           1.0.0    
html5lib                           1.0.1    
hyperlink                          18.0.0   
idna                               2.7      
imageio                            2.4.1    
imagesize                          1.1.0    
incremental                        17.5.0   
ipykernel                          4.9.0    
ipython                            6.5.0    
ipython-genutils                   0.2.0    
ipywidgets                         7.4.1    
isodate                            0.6.0    
isort                              4.3.4    
itsdangerous                       0.24     
jdcal                              1.4      
jedi                               0.12.1   
jeepney                            0.3.1    
Jinja2                             2.10     
jsonschema                         2.6.0    
jupyter                            1.0.0    
jupyter-client                     5.2.3    
jupyter-console                    5.2.0    
jupyter-core                       4.4.0    
jupyterlab                         0.34.9   
jupyterlab-launcher                0.13.1   
keyring                            13.2.1   
kiwisolver                         1.0.1    
lazy-object-proxy                  1.3.1    
llvmlite                           0.24.0   
locket                             0.2.0    
lxml                               4.2.5    
MarkupSafe                         1.0      
matplotlib                         2.2.3    
mc-bin-client                      1.0.1    
mccabe                             0.6.1    
mistune                            0.8.3    
mkl-fft                            1.0.4    
mkl-random                         1.0.1    
more-itertools                     4.3.0    
mpmath                             1.0.0    
msgpack                            0.5.6    
multipledispatch                   0.6.0    
navigator-updater                  0.2.1    
nbconvert                          5.4.0    
nbformat                           4.4.0    
networkx                           2.1      
nltk                               3.3      
nose                               1.3.7    
notebook                           5.6.0    
numba                              0.39.0   
numexpr                            2.6.8    
numpy                              1.15.1   
numpydoc                           0.8.0    
odo                                0.5.1    
olefile                            0.46     
openpyxl                           2.5.6    
packaging                          17.1     
pandas                             0.23.4   
pandocfilters                      1.4.2    
parso                              0.3.1    
partd                              0.3.8    
path.py                            11.1.0   
pathlib2                           2.3.2    
patsy                              0.5.0    
pep8                               1.7.1    
pexpect                            4.6.0    
pickleshare                        0.7.4    
Pillow                             5.2.0    
pip                                10.0.1   
pkginfo                            1.4.2    
pluggy                             0.7.1    
ply                                3.11     
prometheus-client                  0.3.1    
prompt-toolkit                     1.0.15   
psutil                             5.4.7    
ptyprocess                         0.6.0    
py                                 1.6.0    
pyasn1                             0.4.4    
pyasn1-modules                     0.2.2    
pycodestyle                        2.4.0    
pycosat                            0.6.3    
pycparser                          2.18     
pycrypto                           2.6.1    
pycurl                             7.43.0.2 
pyflakes                           2.0.0    
Pygments                           2.2.0    
pylint                             2.1.1    
pyodbc                             4.0.24   
pyOpenSSL                          18.0.0   
pyparsing                          2.2.0    
PySocks                            1.6.8    
pytest                             3.8.0    
pytest-arraydiff                   0.2      
pytest-astropy                     0.4.0    
pytest-doctestplus                 0.1.3    
pytest-openfiles                   0.3.0    
pytest-remotedata                  0.3.0    
python-dateutil                    2.7.3    
python-louvain                     0.15     
pytz                               2018.5   
PyWavelets                         1.0.0    
PyYAML                             3.13     
pyzmq                              17.1.2   
QtAwesome                          0.4.4    
qtconsole                          4.4.1    
QtPy                               1.5.0    
rdflib                             6.0.0    
requests                           2.19.1   
rope                               0.11.0   
ruamel-yaml                        0.15.46  
scikit-image                       0.14.0   
scikit-learn                       0.19.2   
scipy                              1.1.0    
seaborn                            0.9.0    
SecretStorage                      3.1.0    
Send2Trash                         1.5.0    
service-identity                   17.0.0   
setuptools                         40.2.0   
simplegeneric                      0.8.1    
singledispatch                     3.4.0.3  
six                                1.11.0   
snowballstemmer                    1.2.1    
sortedcollections                  1.0.1    
sortedcontainers                   2.0.5    
Sphinx                             1.7.9    
sphinxcontrib-websupport           1.1.0    
spyder                             3.3.1    
spyder-kernels                     0.2.6    
SQLAlchemy                         1.2.11   
statsmodels                        0.9.0    
sympy                              1.2      
tables                             3.4.4    
tap                                0.2      
tblib                              1.3.2    
terminado                          0.8.1    
testpath                           0.3.1    
toolz                              0.9.0    
torch                              1.9.0    
torch-cluster                      1.5.9    
torch-geometric                    1.7.2    
torch-scatter                      2.0.8    
torch-sparse                       0.6.12   
torch-spline-conv                  1.2.1    
tornado                            5.1      
tqdm                               4.26.0   
traitlets                          4.3.2    
Twisted                            18.7.0   
typing-extensions                  3.10.0.2 
unicodecsv                         0.14.1   
urllib3                            1.23     
wcwidth                            0.1.7    
webencodings                       0.5.1    
Werkzeug                           0.14.1   
wheel                              0.31.1   
widgetsnbextension                 3.4.1    
wrapt                              1.10.11  
xlrd                               1.1.0    
XlsxWriter                         1.1.0    
xlwt                               1.3.0    
zict                               0.1.3    
zope.interface                     4.5.0    

```

**Comment by YanghepuLI** [comment]
Thanks for your help.

**Comment by Oceanusity** [comment]
Through the package list, the dependent package typed-argument-parser is not installed, and another package tap is installed which has the same imported name as the typed-argument-parser. I advise you to uninstall the tap and then install the [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser).
