### ISSUE TITLE
 PGExplainer Errors:  explanation for graph classification

### ISSUE THREAD

**Issue by zacharykzhao** [divelab/DIG#73]
When I follow benchmarks/xgraph/pgexplainer_edges.py to train PGExplainer for explanation tasks in graph classification in my personal data, the error happens in assert 
`    
assert out.size(self.node_dim) == edge_mask.size(0)
`

The trace bask give like follows:
`
Traceback (most recent call last):
  File ".pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File ".pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "Documents/Code/GraphResearch/DIG_test/PGExplainer_android/PGExplain_and.py", line 85, in <module>
    pgexplainer.train_explanation_network(train_graphs[:10])
  File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 638, in train_explanation_network
    prob, edge_mask = self.explain(data.x, data.edge_index, embed=emb_dict[gid], tmp=tmp, training=True)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 604, in explain
    logits = self.model(x, edge_index)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 209, in forward
    post_conv = self.conv1(x, edge_index)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 410, in forward
    out = self.propagate(edge_index, x=x[0], size=None)
  File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 498, in propagate
    assert out.size(self.node_dim) == edge_mask.size(0)
AssertionError
`

I found that it happens after 'PGExplainer.__set_masks__' updates 'edge_mask' in my model (I trained the graph classifier follows the gnn_train with GIN_3L). 
The errors happen when I train the PGExplainer.

May I have your suggestion to fix that

**Comment by zacharykzhao** [comment]
> When I follow benchmarks/xgraph/pgexplainer_edges.py to train PGExplainer for explanation tasks in graph classification in my personal data, the error happens in assert ` assert out.size(self.node_dim) == edge_mask.size(0)`
> 
> The trace bask give like follows: `Traceback (most recent call last): File ".pycharm_helpers/pydev/pydevd.py", line 1483, in _exec pydev_imports.execfile(file, globals, locals) # execute the script File ".pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "Documents/Code/GraphResearch/DIG_test/PGExplainer_android/PGExplain_and.py", line 85, in <module> pgexplainer.train_explanation_network(train_graphs[:10]) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 638, in train_explanation_network prob, edge_mask = self.explain(data.x, data.edge_index, embed=emb_dict[gid], tmp=tmp, training=True) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 604, in explain logits = self.model(x, edge_index) File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 209, in forward post_conv = self.conv1(x, edge_index) File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 410, in forward out = self.propagate(edge_index, x=x[0], size=None) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 498, in propagate assert out.size(self.node_dim) == edge_mask.size(0) AssertionError`
> 
> I found that it happens after 'PGExplainer.**set_masks**' updates 'edge_mask' in my model (I trained the graph classifier follows the gnn_train with GIN_3L). The errors happen when I train the PGExplainer.
> 
> May I have your suggestion to fix that

Maybe it's because my graph is a directed graph?

**Comment by zacharykzhao** [comment]
> When I follow benchmarks/xgraph/pgexplainer_edges.py to train PGExplainer for explanation tasks in graph classification in my personal data, the error happens in assert ` assert out.size(self.node_dim) == edge_mask.size(0)`
> 
> The trace bask give like follows: `Traceback (most recent call last): File ".pycharm_helpers/pydev/pydevd.py", line 1483, in _exec pydev_imports.execfile(file, globals, locals) # execute the script File ".pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "Documents/Code/GraphResearch/DIG_test/PGExplainer_android/PGExplain_and.py", line 85, in <module> pgexplainer.train_explanation_network(train_graphs[:10]) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 638, in train_explanation_network prob, edge_mask = self.explain(data.x, data.edge_index, embed=emb_dict[gid], tmp=tmp, training=True) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py", line 604, in explain logits = self.model(x, edge_index) File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 209, in forward post_conv = self.conv1(x, edge_index) File "anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 410, in forward out = self.propagate(edge_index, x=x[0], size=None) File "anaconda3/envs/graph/lib/python3.8/site-packages/dig/xgraph/models/models.py", line 498, in propagate assert out.size(self.node_dim) == edge_mask.size(0) AssertionError`
> 
> I found that it happens after 'PGExplainer.**set_masks**' updates 'edge_mask' in my model (I trained the graph classifier follows the gnn_train with GIN_3L). The errors happen when I train the PGExplainer.
> 
> May I have your suggestion to fix that

I also tried train a GCN classifier. The same error occurs...
